[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_program = "28s5giZcPKoSXbsgycdVeGeuE2hh4u8yDrXwLiLYNpeV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/ore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
